version: 0.2

phases:
  pre_build:
    commands:
    # $AWS_DEFAULT_REGION, $AWS_ACCOUNT_ID, $AWS_DEFAULT_REGION, $IMAGE_REPO_NAME are defined in the CodeBuild setting.
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      # set the environment variables
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest} # set the image tag to the extracted commit hash or "latest" if no commit hash is available
  build:
    commands:
      - echo -e "Build started on `date`\nBuilding the Docker image..."
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG # tag the built docker image
      # check files copied under particular directories
      - docker run $REPOSITORY_URI:latest ls -l /usr/share/nginx/html
      - docker run $REPOSITORY_URI:latest ls -l /usr/share/nginx/html/images
  post_build:
    commands:
      - echo -e "Build completed on `date`\nPushing the Docker image..."
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' "$IMAGE_REPO_NAME" "$REPOSITORY_URI:$IMAGE_TAG" > imagedefinitions.json
artifacts:
  files: imagedefinitions.json